### ISSUE TITLE
请问单文件cpp该如何编译成exe

### ISSUE THREAD

**Issue by sunlewuyou** [3gstudent/Catch-specified-file-s-handle#1]
您好，三好老师，喜欢您的博文，知识点都讲得很透彻明白有案例，您有些小工具只提供了一个cpp的单文件，我装的Visual Studio 2015 不太熟悉怎么将它成功编译成可执行文件，但是我能打开有些github上有.sln文件的工程直接成功编译，但是您这个我编译不了，请你详细指点一下好吗？真的十分感谢了！！

**Comment by 3gstudent** [comment]
https://blog.csdn.net/sinat_36147557/article/details/53301712

**Comment by sunlewuyou** [comment]
非常感谢您的热心回复！
